### ISSUE TITLE
Feature - create new Register and Login screen

### ISSUE THREAD

**Issue by Gierdiaz** [Gierdiaz/Diagier#32]
### Description

To enhance both user experience and interface, we are implementing new screens designed by @VHAlvesS  and @Th-Fernandes. Our goal is to achieve an intuitive and easy-to-use experience.

### TODO

- [x] install tailwindcss into the project
- [x] Create a `sign layout` to reuse the UI in both register and login screens
- [x] Create a `login form` component
- [x] Create a `register form` component
- [x] Connect the backend routes to the components to enable POST requests for user registration/login.

### Considerations

We decided not to use any javascript library or framework. However, it would be nice to use them in the future as we can improve the user experience even morer. For example, we could implement real-time input validation as the user types.

**Comment by Th-Fernandes** [comment]
I believe this feature is ready to be tested as it implements all the news screens in the project. Here are some of the major changes in all these new commits:

- A new layout to be reused in both register and login screens
- A component to display input errors when the server send them back
- Implementation of accessible visual elements such as outlines when an input is in focus mode and navigation through keyboard
- removal of libraries that are not being used anymore (i.e. particlesJs)
- addition of new assets

Since tailwind is now being used for styling the project, it is crucial to run `npm run dev` for vite to handle the UI changes in real-time. Not running this command might break the CSS on even throw a ` ViteManifestNotFoundException`
