### ISSUE TITLE
Feature - create Project Layout

### ISSUE THREAD

**Issue by Th-Fernandes** [Gierdiaz/Diagier#36]
### Description

It is time to create the layout the app uses the most. it should be used for handling the navigation between projects, files, team members and so on. We expect to make it easier to build the majority of the other screens after the creation of this layout.

![project-layout](https://github.com/Gierdiaz/Diagier/assets/74260107/bf092ef8-4c27-4f02-a844-5e76fac26f85)

### TODO

- [ ] set the colors used in the layout into tailwind config
- [ ] link the navigation using `route` function in both aside and header elements
- [ ] import assets into the project
- [ ] set styles for hover and focus states

### Considerations

it seems that the app is advancing towards an SPA strategy. Although, since we are using only blade for handling the client side, it may sacrifice user experience as user needs to wait for the entire page to be rendered with every single navigation. We as a team can discuss this matter later, keeping in mind that the project's still going to work, but it would be nice to take a closer look at it at some point.
